### PR TITLE
Application Command Events

### PR DESCRIPTION
**Pull request by Loliticos**
## About
The events `applicationCommandCreate`, `applicationCommandUpdate` and `applicationCommandDelete` were removed for bots. discord/discord-api-docs#3691

## Status

- [x] These changes have been tested against Discord API or do not contain API change.
- [ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

### CODE REVIEW

**Comment by DjDeveloperr** [comment]
Please fix lint errors before we can merge

**Comment by Loliticos** [comment]
> Please fix lint errors before we can merge

Done, LMK if anything else

**Comment by MierenManz** [comment]
Isn't this technically a breaking Change if we remove these?

**Comment by Loliticos** [comment]
> Isn't this technically a breaking Change if we remove these?

Not really, these events weren't emitted for bots. So they never really "worked"

**Comment by Helloyunho** [comment]
> > Isn't this technically a breaking Change if we remove these?
> 
> Not really, these events weren't emitted for bots. So they never really "worked"

Discord is weird isn't it

**Review by Helloyunho — APPROVED** [review]
lgtm!

**Comment by MierenManz** [comment]
> > Isn't this technically a breaking Change if we remove these?
> 
> Not really, these events weren't emitted for bots. So they never really "worked"

Oh okay yeah then it is fine. Already wondered why this would be a change without technically breaking stuff

**Pull request merged**
