### PR TITLE
Add min_value and max_value slash command options

### PR DESCRIPTION
**Pull request by invalidCards**
## About
Newly added by Discord to add minimum and maximum value constraints to NUMBER and INTEGER slash command options. See also https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure

## Status

- [x] These changes have been tested against Discord API or do not contain API change.
- [ ] This PR includes only documentation changes, no code change.
- [ ] This PR introduces some Breaking changes.

### CODE REVIEW

**Review by DjDeveloperr — APPROVED** [review]
LGTM

**Comment by DjDeveloperr** [comment]
(Canary CI failing is unrelated to PR)

**Review by Helloyunho — APPROVED** [review]
lgtm

**Comment by DjDeveloperr** [comment]
Merge upstream main branch to fix canary CI @invalidCards

**Pull request merged**
