### PR TITLE
Switch Eslint for Deno lint

### PR DESCRIPTION
**Pull request by MierenManz**
## About
Alot of types get fucked because of eslint.
V3 isn't out or being developed yet but I think that switching to deno lint can improve alot of types by default.
I think this because eslint doesn't understand deno's module resolving system and thus get's alot of implicit `any`
deno lint does understand the resolving system and can infer types alot better than eslint.

I think it is best to switch even if v2 will have a limited life cycle

## Status

- [x] These changes have been tested against Discord API or do not contain API change.
- [ ] This PR includes only documentation changes, no code change.
- [x] This PR introduces some Breaking changes. (Could be, idk)

### CODE REVIEW

**Comment by MierenManz** [comment]
I accidently started this from the wrong branch. So it also has changes from args_parser pr :sweat:
I hope that isn't a problem tho...

Lemme know what people think about this cuz then I'll do a second pass and fix as much types and linting warnings as possible

**Comment by Helloyunho** [comment]
you should at least run prettier

**Comment by MierenManz** [comment]
I had alot of comments and I linked all of them. Forgot to put them here. That's why I didn't run prettier

**Comment by MierenManz** [comment]
>I had alot of comments and I linked all of them. Forgot to put them here. That's why I didn't run prettier

src/client/client.ts 280
src/client/shard.ts 22
src/client/shard.ts 46
src/client/shard.ts 134
src/commands/client.ts 82
src/gateway/handlers/reconnect.ts 5
src/gateway/managers/base.ts 14
src/gateway/managers/base.ts 74
src/gateway/managers/emojis.ts 16
src/gateway/rest/bucket.ts 94
src/types/channel.ts 53

These are all the comments I had

**Comment by MierenManz** [comment]
I kinda regret doing this. V2 is gonna be out basically within the next week. So idk if it is worth contingent this.
@DjDeveloperr and @Helloyunho what are your thoughts?

**Comment by MierenManz** [comment]
I would like a reply to my last comment @DjDeveloperr or @Helloyunho :sweat_smile:

**Comment by MierenManz** [comment]
Discussed in discord.
Closing this

**Pull request closed without merging**
