### PR TITLE
feat: Threads

### PR DESCRIPTION
**Pull request by DjDeveloperr**

### CODE REVIEW

**Comment by Cormanz** [comment]
Any updates on this?

**Comment by MierenManz** [comment]
Right now this is not being reviewed because yunho has exams.

These should be done soon tho.
Sorry for the delay that it causes :/

**Comment by 6days9weeks** [comment]
> Any updates on this?

This works iirc. If you really want to use it, you can use Djs branch on his fork, one of my bots is running that and it’s stable ish.

**Comment by Cormanz** [comment]
> > Any updates on this?
> 
> This works iirc. If you really want to use it, you can use Djs branch on his fork, one of my bots is running that and it’s stable ish.

Oh ok, thanks!

**Pull request merged**
